package com.omiyawaki.osrswiki.database // Updated package

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents the status of an article being saved for offline use.
 */
enum class ArticleSaveStatus {
    PENDING,              // Article is queued for download.
    DOWNLOADING_HTML,     // HTML content is being downloaded.
    DOWNLOADING_IMAGES,   // Images and other assets are being downloaded.
    COMPLETE,             // Article and all its assets are successfully saved.
    FAILED                // An error occurred during the saving process.
}

/**
 * Represents a saved OSRS Wiki article's metadata in the local database.
 * This entity stores information necessary for displaying and searching saved articles.
 */
@Entity(
    tableName = "saved_article_entries",
    indices = [Index(value = ["normalized_article_title"])]
)
data class SavedArticleEntry(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    var id: Long = 0,

    @ColumnInfo(name = "article_title")
    var articleTitle: String,

    // Normalized title for accent-insensitive and case-insensitive searching.
    @ColumnInfo(name = "normalized_article_title")
    var normalizedArticleTitle: String,

    // An optional short description or snippet from the article.
    @ColumnInfo(name = "snippet")
    var snippet: String? = null,

    // Timestamp of when the article was saved or last attempted, in milliseconds since epoch.
    @ColumnInfo(name = "timestamp")
    var timestamp: Long = System.currentTimeMillis(),

    // Current status of the offline saving process for this article.
    // Stored as a String, corresponds to ArticleSaveStatus enum names.
    @ColumnInfo(name = "status")
    var status: String = ArticleSaveStatus.PENDING.name
) {
    // Constructor for creating a new entry before insertion,
    // where ID is not yet known and status defaults.
    constructor(
        articleTitle: String,
        normalizedArticleTitle: String,
        snippet: String? = null
        // id is auto-generated
        // timestamp defaults to current time
        // status defaults to PENDING.name
    ) : this(
        id = 0, // Will be auto-generated by Room
        articleTitle = articleTitle,
        normalizedArticleTitle = normalizedArticleTitle,
        snippet = snippet,
        timestamp = System.currentTimeMillis(),
        status = ArticleSaveStatus.PENDING.name
    )
}
