package com.omiyawaki.osrswiki.ui.map

/**
 * Generated by scripts/shared/stamp-map-default-view.py from shared/map-default-view.json.
 */
object osrsMapDefaultView {
    const val GAME_X = 3222.0
    const val GAME_Y = 3218.0
    const val PLANE = 0
    const val GAME_COORD_SCALE = 4.0
    const val GAME_MIN_X = 960.0
    const val GAME_MAX_X = 4224.0
    const val GAME_MIN_Y = 1216.0
    const val GAME_MAX_Y = 12608.0
    const val SOURCE_IMAGE_WIDTH = 13056.0
    const val SOURCE_IMAGE_HEIGHT = 45568.0
    const val TILE_SIZE = 1024.0
    const val MAX_ZOOM = 6
    const val CANVAS_SIZE = 65536.0
    const val LATITUDE = -25.44327461230575
    const val LONGITUDE = -130.2978515625
    const val ZOOM = 7.3414426741929

    fun longitudeForGameX(gameX: Double): Double {
        val px = (gameX - GAME_MIN_X) * GAME_COORD_SCALE
        val nx = px / CANVAS_SIZE
        return -180.0 + nx * 360.0
    }

    fun latitudeForGameY(gameY: Double): Double {
        val py = (GAME_MAX_Y - gameY) * GAME_COORD_SCALE
        val ny = py / CANVAS_SIZE
        return Math.toDegrees(Math.atan(Math.sinh(Math.PI * (1.0 - 2.0 * ny))))
    }
}
